name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: write
  packages: write

jobs:
  release-binary:
    strategy:
      matrix:
        os: [ linux, windows, darwin ] # 需要打包的系统
        arch: [ amd64, arm64 ] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          binary_name: "tinyfs"