name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  contents: write
  packages: write

jobs:
  release-binary:
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64 ]
        exclude:
          - arch: arm64
            os: windows
          - arch: arm64
            os: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          binary_name: "tinyfs"